# Generated by Django 4.1.1 on 2022-09-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='price',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='quantity',
            field=models.IntegerField(default=True),
        ),
    ]
