# Generated by Django 4.1.1 on 2022-09-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_widget_price_widget_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='total',
            field=models.IntegerField(default=True),
        ),
    ]
