# Generated by Django 4.1.1 on 2022-09-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_widget_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widget',
            old_name='total',
            new_name='total_price',
        ),
    ]
